package br.com.v360.purchaseorder.domain.model;

public enum DivergenceType {
    PURCHASE_ORDER_NOT_FOUND,
    PURCHASE_ORDER_CLOSED,
    PURCHASE_ORDER_BLOCKED,
    VENDOR_MISMATCH,
    MATERIAL_NOT_FOUND,
    PURCHASE_ORDER_ITEM_NOT_FOUND,
    MATERIAL_MISMATCH,
    AMBIGUOUS_MATERIAL,
    INVALID_QUANTITY,
    QUANTITY_EXCEEDS_REMAINING,
    PRICE_MISMATCH
}

